INSERT INTO CONTACT (id, birth_date, type, name, phone) VALUES (675, '14/12/2020', 'Contact Type 1', 'Robert', '+55048994649702');
INSERT INTO CONTACT (id, birth_date, type, name, phone) VALUES (986, '14/12/2020', 'Contact Type 2', 'Ana', '+55048994649702');
INSERT INTO CONTACT (id, birth_date, type, name, phone) VALUES (987, '14/12/2020', 'Contact Type 3', 'Pedro', '+55048994649702');
INSERT INTO CONTACT (id, birth_date, type, name, phone) VALUES (941, '14/12/2020', 'Contact Type 1', 'Cris', '+55048994649702');

INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (1, 'false', 'Sunday May 17 at 9:00 PM', 'Second Dock', 5, 675);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (2, 'false', 'Sunday May 18 at 11:00 PM', 'Island Creek', 2, 986);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (3, 'false', 'Friday May 10 at 1:00 PM', 'Fogo the Chao', 5, 987);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (4, 'false', 'Sunday May 17 at 9:00 PM', 'Second Dock', 5, 941);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (5, 'false', 'Sunday May 18 at 11:00 PM', 'Island Creek', 2, 675);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (6, 'false', 'Friday May 10 at 1:00 PM', 'Fogo the Chao', 5, 986);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (7, 'false', 'Sunday May 17 at 9:00 PM', 'Second Dock', 5, 987);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (8, 'false', 'Sunday May 18 at 11:00 PM', 'Island Creek', 2, 941);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (9, 'false', 'Friday May 10 at 1:00 PM', 'Fogo the Chao', 5, 675);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (10, 'false', 'Sunday May 17 at 9:00 PM', 'Second Dock', 5, 986);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (11, 'false', 'Sunday May 18 at 11:00 PM', 'Island Creek', 2, 987);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (12, 'false', 'Friday May 10 at 1:00 PM', 'Fogo the Chao', 5, 941);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (13, 'false', 'Sunday May 17 at 9:00 PM', 'Second Dock', 5, 675);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (14, 'false', 'Sunday May 18 at 11:00 PM', 'Island Creek', 2, 986);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (15, 'false', 'Friday May 10 at 1:00 PM', 'Fogo the Chao', 5, 987);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (16, 'false', 'Sunday May 17 at 9:00 PM', 'Second Dock', 5, 941);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (17, 'false', 'Sunday May 18 at 11:00 PM', 'Island Creek', 2, 675);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (18, 'false', 'Friday May 10 at 1:00 PM', 'Fogo the Chao', 5, 986);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (19, 'false', 'Sunday May 17 at 9:00 PM', 'Second Dock', 5, 941);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (20, 'false', 'Sunday May 18 at 11:00 PM', 'Island Creek', 2, 941);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (21, 'false', 'Friday May 10 at 1:00 PM', 'Fogo the Chao', 5, 675);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (22, 'false', 'Sunday May 17 at 9:00 PM', 'Second Dock', 5, 986);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (23, 'false', 'Sunday May 18 at 11:00 PM', 'Island Creek', 2, 987);
INSERT INTO RESERVATION (id, favorite, description, name, rating, contact_id) VALUES (24, 'false', 'Friday May 10 at 1:00 PM', 'Fogo the Chao', 5, 941);
